topics = [
'guitar production tips',
'bass production tips',
'drum production tips',
'synth production tips',
'vocal production tips',
'songwriting tips',
'mixing tips',
'mastering tips',
'random production tips']

guitar_production_tips = [
"roll off the low (100hz) and high (12k) freqs",	
"don't duck the mids too hard",	
"less gain = more clarity", 	
"try tape saturation after the amp",
"use fresh strings when recording",	
"setup the guitar professionally before recording",
"double-track & pan L/R",
"double-track leads (but not solos)",
"use a stereo widener to clear some room",
"use mid/side compression to make space for vocals",
"highpass & let the bass handle low frequencies",
"use automation to create swells or pads",
"use multiband compression for low frequencies when palm-muting",
"you can fake amp feedback w/ digital amps by fading in a harmonic",
"don't cut off the pick attack when editing",
"try different picks to fix weak playing",
"long reverbs + delays = ambient pads",
"granular resynthesis & looping can make awesome pads",
"reverse & layer for an ethereal sound",
"use noise gates & manual editing to clean up",
"pitch correct guitars for a perfect/robotic sound",
"try different guitar body impulse responses (look online)",
"track with 2 different guitars/amps for a wider sound",
"experiment with weird noises like tapping the body & scraping strings",
"use e-bow for infinite sustained pads",
"layer heavy guitars with synths for doom soundtrack",
"try different flavours of delay like tape, ping pong etc",
"create stutter/glitches by cutting on the grid",
"time stretch before the amp for more precision",
"you can pitch shift quite a lot, distortion hides the artifacts",
"notch 4k and dip 2.5k if using an amp sim",
"use a vocoder for a 'synthey' sound",
"try recording pick attack alongside the DI",
"blend amps/cabs for more control",
"quad track 'large' sections, but keep phase in mind",
"tap the pickup for a kick drum sound",
"note clarity is highly dependant on good picking",
]

bass_production_tips = [
"try blending amped & di signals for the best of both worlds",
"use a DI box for a cleaner DI signal",
"note clarity depends on good picking & playing",
"oversample saturation plugins to avoid excess low frequencies",
"use multiband processing for more control",
"heavily compress/limit the sub band to prevent spiky low-end",
"try adding chorus to the higher band to help blend with the guitars",
"use the same amp as the guitars on the high band to match tonally",
"add 'clank' by running the high band through a guitar amp",
"beware ground hum & cable interference as they sit in the bass register",
"if using digital amp sim, notch 4k and dip 2.5k for harshness",
"use a soft knee compressor to control dynamic/inconsistent playing",
"time-stretch before the amp, distortion will cover the artifacts",
"try layering with a sine synth or pitch-shifted sub",
"if sidechaining to the kick, highpass the sidechain to prevent double-activation",
"if using an amp, try adding tape saturation after to 'soften' the harshness",
"use harmonic exciters like MaxxBass to help translation on small speakers",
"always test bass frequencies in a car",
"use volume automation if the bass is inconsistent/overly dynamic",
"use a mono switch to A/B the mid channel where the bass should be sitting",
"listen on smaller speakers/earphones to check translation",
"use multiband compression on low frequencies when palm-muting",
"when editing, don't cut off the pick transients",
"if the bassist sucks, replace with MIDI (lol)",
"try different bass body impulse responses",
"only distort the upper frequencies, keep the lows & low-mids clean",
]

drum_production_tips = [
"kick EQ: boost 60-80hz for sub, cut 400hz for boxiness",
"snare EQ: 180-200hz fundamental, 1khz honkiness",
"layer snare samples to cut through dense mixes",
"use parallel compression for shells (kick, snare, toms)",
"if writing with MIDI, don't forget ghost notes - they go a long way for realism ",
"always check kick low-end in a car ",
"use a dynamic EQ like Gullfoss to control harsh cymbals ",
"use a tool like Trackspacer to prevent overheads/rooms from burying vocals ",
"tune the kit and always check phase when recording live drums ",
"if writing MIDI, study real drum performances to improve the realism ",
"when writing MIDI drums, use humanization and randomization for velocity & timing",
"throw a trash mic (like a 58) in the room and compress the crap out of it ",
"light saturation can go a long way (tape is preferred)",
"use gating, editing and automation to clean up bleed ",
"downward pitched ping-pong delay on snare can be a cool transition effect",
"snare bombs are just reversed printed reverb, they also make cool transitions",
"2 common pan methods: drummer perspective or audience perspective",
"top-down buss processing is a common method to quickly dial in a good drum mix",
"kick drums with lots of reverb can make a cool impact effect",
"use transient designer effects to help control the 'punchiness' of shells",
"use a slow compressor attack to leave the transients untouched ",
"check the drum mix in mono against the vocals to make sure nothing is clashing",
"'electronic' kicks are usually just a noise burst and a downward-pitching sine-wave ",
]

synth_production_tips = [
"clone existing synth patches with Synplant or MicroMusic",
"layer oscillators w/ multiple octaves for a fuller sound",
"learn how to use ADSRs properly: they are extremely useful for sound-design",
"any sound can be broken up into sine-waves, tools like Loris or SPEAR let you visualize this ",
"noise burst through a filtered delay line (Karplus-Strong) can accurately model guitars & bass ",
"use the Noise Oscillator to add some texture and non-linearity to your synth patches",
"use phase modulation & voicing to create a supersaw",
"electronic kick drums are just a noise burst and a downward pitching sine wave",
"understanding modulators will level up your synth patches, specifically LFOs, ADSRs and Macros",
"pads are just washed out synth patches with very long attack & release times",
"use a step sequencer or LFO to make a patch 'rhythmic'",
"layer a sub-osc sine wave with bass guitar for a rock-solid low-end",
"treat mid-range 'bass' (think dubstep) like electric guitars: distort & pan either side",
"the 'doom' sound can be achieved by layering distorted saw waves with heavy guitars",
"VCVrack is a great free program to dip your toes into Modular Synthesis",
"arpeggiators and other MIDI tools are effective ways to rapidly prototype melodies",
"learn the different types of synthesis, specifically additive, subtractive & wavetable ",
"the 'robot voice' effect is a vocoder, which modulates the audio signal with a synthesizer",
"saturation can go a long way to help synths sound less 'digital'",
"rolling off the high end (15k+) can help reduce the harsh digital sound of synths",
"use mid/side EQ to help prevent midrange synths from burying the vocals ",
"use a plugin like Trackspacer to prevent synths from clashing with vocals",
"use sidechain compression or LFOTool to prevent bass/sub from clashing with Kick ",
"if sidechaining synths, highpass the sidechain input to prevent double-activation",
"use a dynamic EQ like Gullfoss to control harshness in software synths",
"if using saturation on synths, highpass afterwards or use oversampling to prevent aliasing",
"printing and resampling forces you to commit to a sound and can help get the song moving forward",
]

vocal_production_tips = [
"listen to isolated vocal tracks on youtube, you'd be surprised how much reverb/delay is used",
"use a pop filter 3-5 inches from the capsule",
"heavily tune doubles & harmonies but keep the lead vocal natural ",
"dynamic singers (think Chester Bennington) will need a lot of compression",
"compression doesn't just level the dynamics, it brings out interesting textures in the voice ",
"sidechain the reverb & delay to the lead vocal so it isn't buried or washed out ",
"time-align doubles and harmonies, you might need to cut out the consonants as well ",
"roll off the lows and highs for doubles, we just need the midrange frequencies ",
"use a highpass filter before the compressor so it isn't overly affected by plosives/rumble ",
"saturation is an extremely important factor for making vocals sit in a dense mix ",
"when saturating vocals, use Oversampling to prevent the high frequencies from aliasing",
"instant air: boost 12k with a high shelf, then de-ess aggressively",
"use a dynamic EQ like Gullfoss to manage harshness or ringing frequencies",
"automate, automate, automate! it's one of the most important steps for vocals ",
"treat screaming vocals like regular singing, harmonize with different 'types' of screams",
"the 'robot voice' effect is achieved via a Vocoder, which is a type of synthesizer",
"AI singing models have come a long way, try them out if you need a backup singer/harmonies",
"print reverb to a vocal take and reverse it: this gives you that 'haunted' sound",
"sidechain other mid tracks to the vocal to help it cut through",
"use a plugin like Trackspacer to help clear some room for the vocal",
"sidechain vocals to the kick drum for that 'pumping' effect",
"the 'Deftones' vocal sound is an SPX-90 doubler preset, with swimmy delays ",
"position the singer far away from the microphone for that 'hallway shouting' type sound",
"subtly blending a lower octave with the lead vocal can be a great way to thicken it",
"the most important tip for consistent vocal takes is to wait 2-3 hours after waking up before tracking",
"when tracking screaming vocals, high frequency content is a good measure of how fatigued the voice is ",
"you don't need a Neumann, an sm58 can sound amazing with the right vocalist ",
"keep the noise floor as low as possible, compression will raise it up significantly",
"if recorded vocals are noisy, use a tool like Izotope RX to de-noise them ",
]

songwriting_tips = [
"use the recorder app on your phone when inspiration strikes",
"when writing vocal melodies, just hum or mumble as a 'reaction' to the music",
"try writing with a different instrument than usual ",
"play with tempo and key, render out a track and time-stretch it to try different vibes ",
"try to write something every day, the point is to get as many reps as possible ",
"use AI tools to assist in the songwriting process, ask chatGPT for ideas like lyrical concepts or genres",
"use samples and presets to speed up the writing process, then tweak them for your unique sound ",
"'scratch tracks' are an effective way to get ideas down before forgetting them, perfect them later ",
"copy sections and add elements, or take elements away: mr potato head music ",
"try replacing a melody with a different instrument, you might discover a happy accident",
"use randomization tools and plugins as happy accident machines ",
"arpeggiators and step sequences can be great for generating melody ideas ",
"pocket recorders like the Zoom h1 can be useful for capturing ideas & samples on the go ",
"use prepared or unconventional instruments to force your creative muscles ",
"ask chatGPT to generate lyric concepts or themes if you can't think of any ",
"cover songs to deconstruct them and learn better songwriting techniques ",
"try mashing different genres together to force your creative muscles ",
"add creative restrictions like a certain instrument or song structure/key ",
"writing when tired can have a similar effect to alcohol without the hangover ",
"master your DAW: fiddling around with menus will slow down the writing process significantly ",
"use tools like MIDI invert & reverse to generate new melodies ",
"use tools like audio-to-MIDI to generate samples and loops quickly",
"apps like Suno can extend song ideas or generate full songs, just beware of copyright",
"try odd tunings or setups for instruments, this can force you to try new things ",
"try writing in a different DAW or with only stock plugins ",
"use Synplant or MicroMusic to quickly generate synth patches, then make them your own via tweaking",
"keep your phone nearby when you sleep in case you write a dream-banger ",
"try restricting the number of instruments you write with, eg: a full track of percussion or guitar",
"listen to new music, force yourself to try new genres or artists ",
"re-use elements from your previous songs and modify them, this can be a cool throwback ",
"collaborate with other artists, bounce ideas back and forth and try new things",
]

mixing_tips = [
"use volume automation to help choruses and big sections pop",
"automate EQ moves to deal with resonant frequencies in certain sections",
"parallel compression is a great way to add punch to drum shells without squashing transients",
"always always always use a reference track",
"always check the low end in a car ",
"listen to isolate tracks on Youtube to analyze and learn from professionals",
"use multiband compression on the low frequencies for palm mutes ",
"use a dynamic EQ like Gullfoss to dampen harsh frequencies ",
"modern mixes are brighter than you might realize ",
"use mid/side EQ to clear space for vocals",
"check the mix in Mono",
"check the mix on as many different setups as you can",
"top-down buss mixing is a common technique to quickly get a mix off the ground ",
"levels are everything, most work in a mix is just moving faders",
"sidechain reverb and delay to prevent washing out the vocals ",
"limit or heavily compress the sub band to prevent it from spiking around too much ",
"use a stereo widener only on higher frequencies, keep the bass mono ",
"if using saturation plugins, enable Oversampling to prevent high frequencies aliasing ",
"gently highpass any element that doesn't need bass frequencies (vocals, guitars, cymbals etc)",
"layer compressors and let each of them carry some of the load ",
"when dialing in a dry/wet slider, find a sweet spot, then gently back it off some more ",
"using a very subtle room send can help glue everything together",
"avoid mixing with ear fatigue or overly loud speakers ",
"ask producer friends to critique your mixes ",
"let each element do its job eg: don't try to add low-end to the guitars",
"take breaks and re-listen with fresh ears ",
"monitor headroom and make sure each element has enough space to work with ",
"don't cut too many frequencies, this will result in a thin and weak mix ",
"highpass before compression: this prevents low rumble from activating the compressor ",
"high shelf boost into a de-esser for instant air on the vocals ",
"use a tool like Trackspacer to help sidechain elements that are clashing ",
"speakers should sit in an equilateral triangle to you, at ear-level ",
"the most important room treatment is first-reflections, then bass trapping the corners ",
"try not to solo tracks too often, listen in the context of the full mix ",
"try using different amps/cabs for left and right guitars, for a wider stereo image",
"filter the low and high frequencies of vocal doubles to avoid washing out the lead",
"add some spice and sizzle with transition effects, risers, shepherd tones etc",
"fader-ride the lead vocal take to make sure every word is audible",
"save your favourite mixes as templates to re-use across an entire album",
"don't be afraid of presets, they are there to serve as a starting point",
"always check for phase issues ",
"learn your DAW: fumbling around in menus will slow down your workflow significantly",
"use a plugin like Izotope RX to remove noise from bad recordings",
"create different versions of each mix and send them to friends and colleagues for feedback",
]

mastering_tips = [
"limit vs clipping: the former squashes the audio, the latter deletes it",
"avoid mastering with ear fatigue or on an overly loud setup ",
"use multiple reference tracks ",
"check everything in mono ",
"render multiple masters of a single track, and send them to friends for feedback ",
"always listen to the low-end in a car ",
"use a free monitoring tool like Youlean Loudness Meter to check dbfs ",
"listen on as many different setups and speakers as possible ",
"if possible, fix the issue in the mix first ",
"highpass 20hz for any aliased or low-end rumbling, this will affect compression later",
"make sure the track has enough headroom to make adjustments",
"use a dynamic EQ like Gullfoss Master to remove problem frequencies ",
"less is more, be subtle with EQ moves and compression when mastering",
"use a slow, gentle compressor when gluing a mix together",
"if using a stereo widener, make sure it is only affecting high frequencies, keep the bass mono ",
"if using a tape saturator, enable Oversampling to prevent high frequencies from aliasing",
"use visual tools like spectrum analyzers and phase meters alongside your ears ",
"multiband compression or dynamic EQs can help control a spiky low-end",
"use multiple limiters or clippers in series for better control",
"always dither when exporting at a lower bit-depth",
"export to the highest quality possible",
"master at -0.1dB to avoid inter-sample peaking ",
"take breaks and listen with fresh ears",
"automate gain for quiet and loud sections to add some dynamics back into the song",
"tape emulations have come a long way and include things like saturation and hysteresis",
"harmonic exciters (like MaxxBass) can be a great way to translate low-end across listening environments",
"save your favourite mastering chain as a preset and re-use it across the album/EP",
"treat your room: focus on first reflections and bass-trapping the corners",
"keep the speakers in an equilateral triangle to you, at ear-level",
]

random_tips = [
"don't duck the mids too hard for guitar",	
"less gain = more clarity when using guitar amps", 	
"try tape saturation after the guitar amp",
"use fresh strings when recording",	
"setup the guitar/bass professionally before recording",
"double-track & pan guitars L/R",
"double-track leads (but not solos)",
"use mid/side compression to make space for vocals",
"highpass guitars & let the bass handle low frequencies",
"use multiband compression for low frequencies when palm-muting",
"you can fake amp feedback w/ digital amps by fading in a harmonic",
"don't cut off the pick attack when editing guitars/bass",
"try different guitar picks to fix weak playing",
"long reverbs + delays = ambient pads",
"granular resynthesis & looping can make awesome pads",
"reverse & layer elements for an ethereal sound",
"use noise gates & manual editing to clean up recordings",
"pitch correct guitars for a perfect/robotic sound",
"try different guitar body impulse responses (look online)",
"track with 2 different guitars/amps for a wider sound",
"experiment with weird noises like tapping the guitar body & scraping strings",
"use e-bow for infinite sustained pads",
"layer heavy guitars with synths for doom soundtrack",
"try different flavours of delay like tape, ping pong etc",
"create stutter/glitches by cutting on the grid",
"time stretch guitars before the amp for more precision",
"you can pitch shift guitars quite a lot, distortion hides the artifacts",
"notch 4k and dip 2.5k for digital amp sims",
"use a vocoder on guitars for a 'synthey' sound",
"try recording pick attack alongside the guitar DI",
"blend guitar amps/cabs for more control",
"quad track 'large' sections for guitars, but keep phase in mind",
"tap the guitar pickup for a kick drum sound",
"note clarity is highly dependant on good picking when tracking guitars",
"try blending amped & di signals for the best of both worlds",
"use a DI box for a cleaner DI signal",
"use multiband processing on bass for more control",
"heavily compress/limit the sub band to prevent spiky low-end",
"try adding chorus to the higher band to help blend bass with the guitars",
"use the same amp as the guitars on the high band for bass to match tonally",
"add 'clank' to bass by running the high band through a guitar amp",
"beware ground hum & cable interference as they sit in the low register",
"try layering bass with a sine synth or pitch-shifted sub",
"if sidechaining bass to the kick, highpass the sidechain to prevent double-activation",
"always test bass frequencies in a car",
"when editing bass, don't cut off the pick transients",
"if the bassist sucks, replace with MIDI (lol)",
"try different bass body impulse responses",
"only distort the upper frequencies, keep the lows & low-mids clean",
"kick EQ: boost 60-80hz for sub, cut 400hz for boxiness",
"snare EQ: 180-200hz fundamental, 1khz honkiness",
"layer snare samples to cut through dense mixes",
"use parallel compression for shells (kick, snare, toms)",
"if writing with MIDI, don't forget ghost notes - they go a long way for realism ",
"always check kick low-end in a car ",
"use a dynamic EQ like Gullfoss to control harsh cymbals ",
"use a tool like Trackspacer to prevent overheads/rooms from burying vocals ",
"tune the kit and always check phase when recording live drums ",
"if writing MIDI, study real drum performances to improve the realism ",
"when writing MIDI drums, use humanization and randomization for velocity & timing",
"throw a trash mic (like a 58) in the room and compress the crap out of it ",
"light saturation can go a long way (tape is preferred)",
"use gating, editing and automation to clean up bleed ",
"downward pitched ping-pong delay on snare can be a cool transition effect",
"snare bombs are just reversed printed reverb, they also make cool transitions",
"2 common pan methods: drummer perspective or audience perspective",
"top-down buss processing is a common method to quickly dial in a good drum mix",
"kick drums with lots of reverb can make a cool impact effect",
"use transient designer effects to help control the 'punchiness' of shells",
"use a slow compressor attack to leave the transients untouched ",
"check the drum mix in mono against the vocals to make sure nothing is clashing",
"'electronic' kicks are usually just a noise burst and a downward-pitching sine-wave ",
"clone existing synth patches with Synplant or MicroMusic",
"layer oscillators w/ multiple octaves for a fuller sound",
"learn how to use ADSRs properly: they are extremely useful for sound-design",
"any sound can be broken up into sine-waves, tools like Loris or SPEAR let you visualize this ",
"noise burst through a filtered delay line (Karplus-Strong) can accurately model guitars & bass ",
"use the Noise Oscillator to add some texture and non-linearity to your synth patches",
"use phase modulation & voicing to create a supersaw",
"electronic kick drums are just a noise burst and a downward pitching sine wave",
"understanding modulators will level up your synth patches, specifically LFOs, ADSRs and Macros",
"pads are just washed out synth patches with very long attack & release times",
"use a step sequencer or LFO to make a patch 'rhythmic'",
"layer a sub-osc sine wave with bass guitar for a rock-solid low-end",
"treat mid-range 'bass' (think dubstep) like electric guitars: distort & pan either side",
"the 'doom' sound can be achieved by layering distorted saw waves with heavy guitars",
"VCVrack is a great free program to dip your toes into Modular Synthesis",
"arpeggiators and other MIDI tools are effective ways to rapidly prototype melodies",
"learn the different types of synthesis, specifically additive, subtractive & wavetable ",
"the 'robot voice' effect is a vocoder, which modulates the audio signal with a synthesizer",
"saturation can go a long way to help synths sound less 'digital'",
"rolling off the high end (15k+) can help reduce the harsh digital sound of synths",
"use mid/side EQ to help prevent midrange synths from burying the vocals ",
"use a plugin like Trackspacer to prevent synths from clashing with vocals",
"use sidechain compression or LFOTool to prevent bass/sub from clashing with Kick ",
"if sidechaining synths, highpass the sidechain input to prevent double-activation",
"use a dynamic EQ like Gullfoss to control harshness in software synths",
"if using saturation on synths, highpass afterwards or use oversampling to prevent aliasing",
"printing and resampling forces you to commit to a sound and can help get the song moving forward",
"listen to isolated vocal tracks on youtube, you'd be surprised how much reverb/delay is used",
"use a pop filter 3-5 inches from the capsule",
"heavily tune doubles & harmonies but keep the lead vocal natural ",
"dynamic singers (think Chester Bennington) will need a lot of compression",
"compression doesn't just level the dynamics, it brings out interesting textures in the voice ",
"sidechain the reverb & delay to the lead vocal so it isn't buried or washed out ",
"time-align doubles and harmonies, you might need to cut out the consonants as well ",
"roll off the lows and highs for doubles, we just need the midrange frequencies ",
"use a highpass filter before the compressor so it isn't overly affected by plosives/rumble ",
"saturation is an extremely important factor for making vocals sit in a dense mix ",
"when saturating vocals, use Oversampling to prevent the high frequencies from aliasing",
"instant air: boost 12k with a high shelf, then de-ess aggressively",
"use a dynamic EQ like Gullfoss to manage harshness or ringing frequencies",
"automate, automate, automate! it's one of the most important steps for vocals ",
"treat screaming vocals like regular singing, harmonize with different 'types' of screams",
"the 'robot voice' effect is achieved via a Vocoder, which is a type of synthesizer",
"AI singing models have come a long way, try them out if you need a backup singer/harmonies",
"print reverb to a vocal take and reverse it: this gives you that 'haunted' sound",
"sidechain other mid tracks to the vocal to help it cut through",
"use a plugin like Trackspacer to help clear some room for the vocal",
"sidechain vocals to the kick drum for that 'pumping' effect",
"the 'Deftones' vocal sound is an SPX-90 doubler preset, with swimmy delays ",
"position the singer far away from the microphone for that 'hallway shouting' type sound",
"subtly blending a lower octave with the lead vocal can be a great way to thicken it",
"the most important tip for consistent vocal takes is to wait 2-3 hours after waking up before tracking",
"when tracking screaming vocals, high frequency content is a good measure of how fatigued the voice is ",
"you don't need a Neumann, an sm58 can sound amazing with the right vocalist ",
"keep the noise floor as low as possible, compression will raise it up significantly",
"if recorded vocals are noisy, use a tool like Izotope RX to de-noise them ",
"use the recorder app on your phone when inspiration strikes",
"when writing vocal melodies, just hum or mumble as a 'reaction' to the music",
"try writing with a different instrument than usual ",
"play with tempo and key, render out a track and time-stretch it to try different vibes ",
"try to write something every day, the point is to get as many reps as possible ",
"use AI tools to assist in the songwriting process, ask chatGPT for ideas like lyrical concepts or genres",
"use samples and presets to speed up the writing process, then tweak them for your unique sound ",
"'scratch tracks' are an effective way to get ideas down before forgetting them, perfect them later ",
"copy sections and add elements, or take elements away: mr potato head music ",
"try replacing a melody with a different instrument, you might discover a happy accident",
"use randomization tools and plugins as happy accident machines ",
"arpeggiators and step sequences can be great for generating melody ideas ",
"pocket recorders like the Zoom h1 can be useful for capturing ideas & samples on the go ",
"use prepared or unconventional instruments to force your creative muscles ",
"ask chatGPT to generate lyric concepts or themes if you can't think of any ",
"cover songs to deconstruct them and learn better songwriting techniques ",
"try mashing different genres together to force your creative muscles ",
"add creative restrictions like a certain instrument or song structure/key ",
"writing when tired can have a similar effect to alcohol without the hangover ",
"master your DAW: fiddling around with menus will slow down the writing process significantly ",
"use tools like MIDI invert & reverse to generate new melodies ",
"use tools like audio-to-MIDI to generate samples and loops quickly",
"apps like Suno can extend song ideas or generate full songs, just beware of copyright",
"try odd tunings or setups for instruments, this can force you to try new things ",
"try writing in a different DAW or with only stock plugins ",
"use Synplant or MicroMusic to quickly generate synth patches, then make them your own via tweaking",
"keep your phone nearby when you sleep in case you write a dream-banger ",
"try restricting the number of instruments you write with, eg: a full track of percussion or guitar",
"listen to new music, force yourself to try new genres or artists ",
"re-use elements from your previous songs and modify them, this can be a cool throwback ",
"collaborate with other artists, bounce ideas back and forth and try new things",
"use volume automation to help choruses and big sections pop",
"automate EQ moves to deal with resonant frequencies in certain sections",
"parallel compression is a great way to add punch to drum shells without squashing transients",
"always always always use a reference track",
"listen to isolate tracks on Youtube to analyze and learn from professionals",
"use a dynamic EQ like Gullfoss to dampen harsh frequencies ",
"modern mixes are brighter than you might realize ",
"use mid/side EQ to clear space for vocals",
"check the mix in Mono",
"check the mix on as many different setups as you can",
"top-down buss mixing is a common technique to quickly get a mix off the ground ",
"levels are everything, most work in a mix is just moving faders",
"sidechain reverb and delay to prevent washing out the vocals ",
"limit or heavily compress the sub band to prevent it from spiking around too much ",
"use a stereo widener only on higher frequencies, keep the bass mono ",
"if using saturation plugins, enable Oversampling to prevent high frequencies aliasing ",
"gently highpass any element that doesn't need bass frequencies (vocals, guitars, cymbals etc)",
"layer compressors and let each of them carry some of the load ",
"when dialing in a dry/wet slider, find a sweet spot, then gently back it off some more ",
"using a very subtle room send can help glue everything together",
"avoid mixing with ear fatigue or overly loud speakers ",
"ask producer friends to critique your mixes ",
"let each element do its job eg: don't try to add low-end to the guitars",
"take breaks and re-listen with fresh ears ",
"monitor headroom and make sure each element has enough space to work with ",
"don't cut too many frequencies, this will result in a thin and weak mix ",
"highpass before compression: this prevents low rumble from activating the compressor ",
"high shelf boost into a de-esser for instant air on the vocals ",
"use a tool like Trackspacer to help sidechain elements that are clashing ",
"speakers should sit in an equilateral triangle to you, at ear-level ",
"the most important room treatment is first-reflections, then bass trapping the corners ",
"try not to solo tracks too often, listen in the context of the full mix ",
"try using different amps/cabs for left and right guitars, for a wider stereo image",
"filter the low and high frequencies of vocal doubles to avoid washing out the lead",
"add some spice and sizzle with transition effects, risers, shepherd tones etc",
"fader-ride the lead vocal take to make sure every word is audible",
"save your favourite mixes as templates to re-use across an entire album",
"don't be afraid of presets, they are there to serve as a starting point",
"always check for phase issues ",
"learn your DAW: fumbling around in menus will slow down your workflow significantly",
"use a plugin like Izotope RX to remove noise from bad recordings",
"create different versions of each mix and send them to friends and colleagues for feedback",
"limit vs clipping: the former squashes the audio, the latter deletes it",
"avoid mastering with ear fatigue or on an overly loud setup ",
"use multiple reference tracks ",
"check everything in mono ",
"render multiple masters of a single track, and send them to friends for feedback ",
"use a free monitoring tool like Youlean Loudness Meter to check dbfs ",
"listen on as many different setups and speakers as possible ",
"if possible, fix the issue in the mix first ",
"highpass 20hz for any aliased or low-end rumbling, this will affect compression later",
"make sure the track has enough headroom to make adjustments",
"use a dynamic EQ like Gullfoss Master to remove problem frequencies ",
"less is more, be subtle with EQ moves and compression when mastering",
"use a slow, gentle compressor when gluing a mix together",
"if using a stereo widener, make sure it is only affecting high frequencies, keep the bass mono ",
"if using a tape saturator, enable Oversampling to prevent high frequencies from aliasing",
"use visual tools like spectrum analyzers and phase meters alongside your ears ",
"multiband compression or dynamic EQs can help control a spiky low-end",
"use multiple limiters or clippers in series for better control",
"always dither when exporting at a lower bit-depth",
"export to the highest quality possible",
"master at -0.1dB to avoid inter-sample peaking ",
"take breaks and listen with fresh ears",
"automate gain for quiet and loud sections to add some dynamics back into the song",
"tape emulations have come a long way and include things like saturation and hysteresis",
"harmonic exciters (like MaxxBass) can be a great way to translate low-end across listening environments",
"save your favourite mastering chain as a preset and re-use it across the album/EP",
"treat your room: focus on first reflections and bass-trapping the corners",
"keep the speakers in an equilateral triangle to you, at ear-level",
]

